### ISSUE TITLE
Proposals for app icons

### ISSUE THREAD

**Issue by dusansimic** [somepaulo/MoreWaita#1]
I have some proposals for future app icons.

- [x] Facebook Messenger (#16)
- [x] Element
- [x] Slack
- [x] Viber
- [x] [Insomnia](https://insomnia.rest/)
- [x] Electron
- [x] Minecraft
- [x] [Firewall](https://firewalld.org/)
- [x] Discord and Discord Canary (#14 and #15)
- [x] OpenJDK 11 and 8 (just a link to the existing icon will fix it, 11 and 8 are still supported)
- [x] VirtualBox
- [x] Bitwarden
- [x] Chromium
- [x] Firefox Developer Edition
- [x] Spotify
- [x] Eclipse
- [x] Vim
- [x] NeoVim
- [x] VSCodium
- [x] Mozilla Thunderbird
- [x] Microsoft Teams
- [x] Fish shell
- [x] Mattermost
- [x] Steam
- [x] GitHub Desktop
- [x] JetBrains Software
- [x] Android Studio

**Comment by somepaulo** [comment]
Spotify is there from the start.
The others will be coming along as I get time to work on them. Feel free to contribute.

**Comment by dusansimic** [comment]
Sorry, haven't noticed it 😅. Some icons seem to have a really thin "3d effect". To me that is kind of a staple of GNOME icons. Do they look bad when they are a bit "thicker" or is something else the reason for the really thin effect?

**Comment by Midou36O** [comment]
[] Strawberry (fork of Clementine)
[] Fl Studio

**Comment by mrquantumoff** [comment]
- [ ] Discord
- [ ] Discord Canary
- [ ] Telegram

**Comment by dusansimic** [comment]
@mrquantumoff Telegram already exists

**Comment by somepaulo** [comment]
> Do they look bad when they are a bit "thicker" or is something else the reason for the really thin effect?

I don't really know. I just followed what Gnome designers did with their original icons (and wrote in several blog posts about Adwaita icon design). Browser icons are big and round with a thin (1px) 'thickness' like Web/Epiphany. Then there are lots of square icons with a 2px 'thickness', and then there are some other icons that have a 3px or bigger 'thickness' like evince for some reason and things that have to have a bigger 'thickness' because of what they represent - printer, mailbox, trash can, etc... Based on all this, I decided to stick with the 2px 'thickness' as a rule of thumb default, making exceptions for browsers and 'thick' icons. I generally like the result, but I think that Office icons would look better 'thinner' maybe.

**Comment by somepaulo** [comment]
> OpenJDK 11 and 8 (just a link to the existing icon will fix it, 11 and 8 are still supported)

I've added multiple symlinks for different versions of Java (including Sun and Oracle) and of LibreOffice in the latest commits. They're all included in v1.0.0

**Comment by nevack** [comment]
JetBrains IDEs + Android Studio will be nice to have :eyes:

**Comment by Anifyuli** [comment]
I wish that icons can be add on this projects

- [ ] Nvidia X Server Settings
- [ ] Trash icon from Dash to Dock Extension (it seem buggy same as base of this icon, Adwaita because it have square background)
- [ ] dConf Editor
- [ ] OBS Studio
- [ ] Scrcpy
- [ ] VirtualBox

Thanks for your next update

**Comment by dusansimic** [comment]
@Anifyuli dConf Editor already has an updated icon on version 43.0

**Comment by Anifyuli** [comment]
> @Anifyuli dConf Editor already has an updated icon on version 43.0

Oh I get your point, but in my system it can't change my dConf Editor icon

**Comment by Anifyuli** [comment]
> @Anifyuli dConf Editor already has an updated icon on version 43.0

Oh I get your point, but in my system it can't change my dConf Editor icon

**Comment by somepaulo** [comment]
> Trash icon from Dash to Dock Extension (it seem buggy same as base of this icon, Adwaita because it have square background)
> dConf Editor

We're following upstream. Since Adwaita provides the Trash icon, we don't override it. dConf editor has a new compliant icon in its latest version. When you update sConf editor, you'll get the new icon.

> OBS Studio
It's there from day one

**Comment by Anifyuli** [comment]
Oh I see. But I have request to change trash icon be better without square background same as on other icons, such as Yaru (Adwaita-based too) and GNOME old icons

**Comment by dusansimic** [comment]
@Anifyuli 

>But I have request to change trash icon be better without square background same as on other icons, such as Yaru (Adwaita-based too) and GNOME old icons

From what I understand, aim of MoreWaita is to be a supplemental icon theme for GNOME user with icons for third party apps that don't have and don't plan on having GNOME/Adwaita styled icons (info about what that style is like can be found in #3). The whole idea is to have those square backgrounds, that's the new GNOME design. If you prefer the old GNOME design, this icon pack is probably not for you.

You could look on the web weather there are already some icon packs that give you the old GNOME icon design but if there are none, you could always make your own by downloading old icons from program repos (most GNOME apps have icons stored in their repos so you can find old icons there too).

**Comment by somepaulo** [comment]
> But I have request to change trash icon

The purpose of this theme is to complement Adwaita, not to modify it. Won't do. Sorry.

**Comment by Anifyuli** [comment]
Ok, Mister. Thanks for your dedication to make this useful project

**Comment by somepaulo** [comment]
> Nicotine+ (if you think the icon isn't Adwaita-enough. I'm not sure)

I think that one's pretty much compliant. DOn't see how I could modify it.

**Comment by somepaulo** [comment]
> The new Element icon doesn't support the Flatpak. It should be symlinked to im.riot.Riot

Fixed in git. Pushing release.

**Comment by somepaulo** [comment]
> OSM Scout Server
> Pure Maps

@julianfairfax wasn't able to install those and no time to debug. Can you point me to the original icons? No idea how they look...

**Comment by somepaulo** [comment]
> When will new icons added in the git be published as a release?

When all planned fixes/modifications are implemented.

> The new Standard Notes icon is also a bit tall and has odd edges.

Like this one ☝️

And also when enough new icons are added to make the release worthy and not spam the version numbering system with minor fixes every few days. That's what git is for, after all.

But if you want an ETA, based on my work schedule (this theme is my hobby), I'd say a week or two, ish, give or take...

**Comment by dusansimic** [comment]
@julianfairfax you're always free to manually install the theme by cloning the git repo and just pulling new commits every day or two to get the latest icons :). That's how the AUR git package works actually

**Comment by somepaulo** [comment]
> Fl studio

Since there's no native implementation, we cannot be sure of the proper icon name, of where to place it and whether it would get picked up, nor are there many solutions to directly launching wine apps with regular desktop shortcuts, AFAIK. Other themes don't have this icon either. I guess it's not worth the effort. Dropping it.

**Comment by K4rakara** [comment]
Could we get one for VSCodium? I personally like its logo much more than the VSCode logo, and use VSCodium.

**Comment by dusansimic** [comment]
@K4rakara I'll see if I can cobble something together later today. If there is a svg file of the icon, it should be fairly easy to do.

**Comment by somepaulo** [comment]
> If there is a svg file of the icon, it should be fairly easy to do.

Found one, did the icon. Should probably do one for Code-OSS too. I'll be doing the editors/IDE's you mentioned in your original issue post this week.

**Comment by somepaulo** [comment]
> Could we get one for VSCodium?

@K4rakara that's now in git and will make it into the next release in a couple of weeks.

**Comment by somepaulo** [comment]
> Microsoft Teams

It's being [discontinued](https://office365itpros.com/2022/09/19/teams-pwa-linux-client/) as a full-fledged app in December, and replaced by a PWA that's already available. I think I figured out the icon name constant for the PWA. The Edge icon is named `msedge-cifhbcnohmdccbgoicgdjpfamggdegmo-Default`. The Chrome one is `chrome-cifhbcnohmdccbgoicgdjpfamggdegmo-Default`. Now I just need to figure all the supported browser variables (the only part in the icon name that changes depending on the browser you use to create the PWA). Will try that and see if it works.

**Comment by somepaulo** [comment]
> It looks like pixelated with white

That looks exactly like the Nautilus rendering issue at medium scale. That doesn't seem to affect the dash though. The icons are `.svg` though, can't have aliasing by themselves. Can you check if other icons have similar issues? This particular icon is based on GNOME Notes (bijiben). Would be great if you could test the two icons side by side with default shell settings and no extensions enabled.

**Comment by somepaulo** [comment]
> Looks fine. Not sure why

Thank you for testing.
I think I get where the white pixels are coming from. The blue part is directly on top of the original full-size part (from the bijiben icon). So when it anti-aliases at small sizes, its anti-aliasing is overlaid on top of the white layer's anti-aliasing, and so it transpires as white from beneath. I'll cut the white layer to below the corners. That should do it.

**Comment by somepaulo** [comment]
> Looks fine. Not sure why

Fixed in [commit 978289e](https://github.com/somepaulo/MoreWaita/commit/978289ef8104a4b9f0ced27087d0b9b98087ba73)

**Comment by Anifyuli** [comment]
Requested icon 
- [ ] Htop

**Comment by dusansimic** [comment]
@Anifyuli htop and nvidia settings are already added https://github.com/somepaulo/MoreWaita/commit/6f2d64bc0ae51d33d83f1db8f1ff90b40a4a8904 https://github.com/somepaulo/MoreWaita/commit/064936df0602addd4d0eb8b54164b280609257e8

**Comment by Anifyuli** [comment]
Hmmm, but in Fedora COPR package htop & Nvidia Settings haven't style icon theming

**Comment by dusansimic** [comment]
@Anifyuli htop icon has been added only a few days ago while the latest release is over 3 weeks old. Nvidia settings icon is in the latest release but the copr pacakge is quite outdated now since I forgot to update it so I'll do that now, thanks for notifying.

I'd just like to point out that the copr package and MoreWaita project are unrelated. I maintain the copr package but it's not an official package maintained by the MoreWaita project. If there are any issues with the copr package (i.e. it's outdated) it should be reported to the copr repository where the package is hosted, not the MoreWaita bug tracker.

**Comment by Anifyuli** [comment]
Oh, I see. Thanks for your explanation, Mister

**Comment by Anifyuli** [comment]
Requested icon
- [ ] Zotero

**Comment by somepaulo** [comment]
> * Solanum

MoreWaita does not theme Gnome or Gnome Circle apps' icons as they all comply to Gnome design specifications by default.

**Comment by Anifyuli** [comment]
Oh, I get it. Thanks for your explanation, Mister

**Comment by jpkhawam** [comment]
do you plan on adding mimetypes? I dislike how most files (e.g. `.cpp`, `.rs`, `.toml`, `.md`) look identical to `.txt` files

**Comment by jpkhawam** [comment]
I would also like to propose the following apps
- [ ] Shotwell
- [ ] Virtual Machine Manager
- [ ] Proton VPN

and the following Jetbrains IDEs:
- [ ] CLion
- [ ] IntelliJ IDEA
- [ ] WebStorm
- [ ] PyCharm

(there are more obviously but I believe these are the most popular

**Comment by dusansimic** [comment]
> do you plan on adding mimetypes? I dislike how most files (e.g. .cpp, .rs, .toml, .md) look identical to .txt files

I LOVE this idea! It would really complete the icon pack. It won't be yet another GNOME styled icon theme.

> and the following Jetbrains IDEs:

Already added :) https://github.com/somepaulo/MoreWaita/commit/c9536bb79f8d80b7878b85827bfc57b845e7df75

It's present in the latest release https://github.com/somepaulo/MoreWaita/releases/tag/v43.2

**Comment by jpkhawam** [comment]
@dusansimic my bad! I downloaded the Copr and didn't notice it isn't up to date yet!

**Comment by dusansimic** [comment]
> @dusansimic my bad! I downloaded the Copr and didn't notice it isn't up to date yet!

No problem! I've only tested the rpm package just now and will trigger the build so it should be available shortly.

**Comment by somepaulo** [comment]
> do you plan on adding mimetypes? I dislike how most files (e.g. `.cpp`, `.rs`, `.toml`, `.md`) look identical to `.txt` files

Yes. It's a whole new endeavour, but yes.
In fact, I've already started with VirtualBox mimes. They're in the theme.

Can you add a comment here with a list of the most needed mimetypes? There are hundreds of them, and I'm at a loss after the obvious php/js/css/html/json/xml/md list.

**Comment by somepaulo** [comment]
> It won't be yet another GNOME styled icon theme.

AFAIK, there are only two other projects like this. One overrides Gnome native icons as well, both have much less icons, and neither is actively maintained. So it's safe to say we're on a good track here ))

Still, mimetypes shall be!

If only we could solve the disappearing icons issue too...

**Comment by sharpordie** [comment]
How about Figma, DBeaver and JDownloader?

- [ ] Figma
- [ ] DBeaver
- [ ] JDownloader

**Comment by Slomo17** [comment]
I would like to see one for

- [ ] Texstudio

i looks really out of place in gnome

**Comment by rene-coty** [comment]
It would be great to have icons for

- [ ] Freetube (Youtube client)
- [ ] Spyder (Python IDE)
- [ ] Geany (GTK+ IDE)
- [ ] Headlines (Reddit client)
- [ ] Saber (handwritten notes)
- [ ] Cawbird (Twitter client)
- [ ] Abiword

**Comment by TylerMS887** [comment]
[ ] Qt5 Configuration Tool
[ ] balenaEtcher

**Comment by jpkhawam** [comment]
@somepaulo 
> Can you add a comment here with a list of the most needed mimetypes? There are hundreds of them, and I'm at a loss after the obvious php/js/css/html/json/xml/md list (and now the ones you mention too).

These are some common file types, I didn't include any code files (`.cpp`, `.py`, etc) as I think those are more obvious

- android apk packages `.apk`
- archives and zip files `.zip`, `.tar.gz`, `.7z`, etc
- image files in case user does not have thumbnails on `.png`, `.jpg`, `.jpeg`, etc
- microsoft office files `.docx`, `.xlsx`, `.pptx`, etc
- pdf documents `.pdf`
- photoshop documents `.psd`
- gimp documents `.xcf`
- flatpaks and snaps `.flatpak`, `.snap`
- rpm and deb packages `.rpm`, `.deb`
- libreoffice documents `.odt`, `.ods`, etc
- optical disc image files `.iso`
- audio files `.mp3`, `.m4a`, etc
- video files `.webm`, `.mp4`, etc

**Comment by rahul-singh-sandhu** [comment]
I have another proposal for folder icons; An appimage/applications folder icon. I have never done any sort of graphics project or something, but I would love to try, an would really appreciate if somebody could let me know whether they use gimp, and the file size, and a few tips if you have any. Thank you :)

**Comment by rahul-singh-sandhu** [comment]
Oh, also I was just looking at the file list above, and i think it would be cool to have a:

- Python folder
- C Folder
- C++ Folder
- Rust Folder
- Go Folder
- Java Folder
(Any other languages somebody might be interested in.)

**Comment by Protrikk** [comment]
An icon for Prism Launcher would be nice

**Comment by somepaulo** [comment]
> These are some common file types

Thank you!
I'm not sure having a bunch of different mimetypes for different types of archives, videos, audios, and documents is a good thing. Adwaita already covers all of these with generic icons. With some notable exceptions like apk's, iso's and packages, I don't think there's real value to visually differentiating one archive or image type from another. But I'm open to discussion.

**Comment by somepaulo** [comment]
> would really appreciate if somebody could let me know whether they use gimp

The icons are vector graphics done in Inkscape and saved as plain svg. The nominal size is 128x128 px. If you know your way around Inkscape I suggest you edit some of the Adwaita/MoreWaita icons to get an idea of how they're constructed.

**Comment by LeFloatyPancake** [comment]
Would be nice to have icons for media related apps:

- [ ] MediaInfo
- [ ] Fre:ac
- [ ] Spek
- [ ] Foobar2000 (Not linux native but could use some adwaita love)

Thanks for this wonderful icon theme

**Comment by vitorfg8** [comment]
Would be nice to have these icons:

- [ ] Todoist
- [ ]  [New Android Studio icon](https://1.bp.blogspot.com/-LgTa-xDiknI/X4EflN56boI/AAAAAAAAPuk/24YyKnqiGkwRS9-_9suPKkfsAwO4wHYEgCLcBGAsYHQ/s0/image9.png)
- [ ] Folder color variants

**Comment by jpkhawam** [comment]
> Adwaita already covers all of these with generic icons [...] I don't think there's real value to visually differentiating one archive or image type from another.

I agree with you, no need to override the icons that already exist. I included as much as I can to check later what exists and what doesn't because I do have thumbnails on for most of these, so I was unsure what they would show up as. If you would like, I can write a new list excluding the ones that don't need new icons

**Comment by sukhmeetbawa** [comment]
Would be nice to have these icons:
- [ ] Yuzu 
Icon: https://raw.githubusercontent.com/flathub/org.yuzu_emu.yuzu/master/org.yuzu_emu.yuzu.svg
Flatpak Name: org.yuzu_emu.yuzu
- [ ]  UnityHub
Icon: https://preview.redd.it/81nwobjayd181.png?width=512&format=png&auto=webp&v=enabled&s=ecd4ebafcc1e81910b2a80c0357e6e4054e86069
Flatpak Name: com.unity.UnityHub
- [ ] Unity Editor
Icon: https://preview.redd.it/vtzpl5c9yd181.png?width=512&format=png&auto=webp&v=enabled&s=84edccb24d07745fd46bd5edd1783f318ceea402

**Comment by dusansimic** [comment]
> I'm not sure having a bunch of different mimetypes for different types of archives, videos, audios, and documents is a good thing. Adwaita already covers all of these with generic icons. With some notable exceptions like apk's, iso's and packages, I don't think there's real value to visually differentiating one archive or image type from another. But I'm open to discussion.

I've just come across two things. Adwaita uses an "unknown executable" icon for the json files and an archive icon for rpm packages (I'm not sure weather it's the same for other package formats).

The json files could get it's own icon since it's a fairly well know and widespread format (maybe have a single icon for various human readable data files like json, xml, toml, yaml...). Regarding the Linux package files, it would be useful to distinguish them from regular archive files. People rarely just open Linux installation packages as archives compared to compressed archives which are opened fairly often or just unpacked.

It would also be nice to note that [Yaru icon theme](https://github.com/ubuntu/yaru/tree/master/icons/Yaru/256x256/mimetypes) has icons for various archive and source code types which have their own mime types. That would mean there would need to be a fair amount of work to design and maintain all of those icons but it would really improve the overall experience on the GNOME de (imho).

**Comment by Aylur** [comment]
Would love to see these.
- [ ] Bitwig Studio
- [ ] Battle.net

**Comment by erlefloch** [comment]
For debian and debian-based distros users, it would be nice to have a morewaita icon for:

- [ ] Synaptic Package Manager

**Comment by Mofiqul** [comment]
I would love see 
- [ ] Qutebrowser

**Comment by wroyca** [comment]
It would be nice see:

- [ ] Sublime Text
- [ ] Sublime Merge

**Comment by somepaulo** [comment]
> * Synaptic Package Manager

This should now use the Gnome Software icon (only in the git version of the theme, atm)

**Comment by Jegah** [comment]
- [ ] Heroic Game Launcher
- [ ] TexStudio
- [ ] mime for .tex files

The first one is a Game Launcher for Epic and GOG. TeXstudio is a LaTeX document editor and .tex are the files for it (often used in university). The mime type could be done similarly to .md files, with .tex inside the default text file icon.

**Comment by somepaulo** [comment]
I'm locking this issue for new comments as it's becoming difficult to follow.
Please add new icon requests as new issues.
All icons requested here will be added to the theme eventually and ticked off in this issue, which will be closed when all icons are done.

**Comment by somepaulo** [comment]
> Would love to see these.
> 
>     * [ ]  Battle.net

There's no direct installer for Arch, so I can't get the actual icon. Please file a separate icon request.

**Comment by somepaulo** [comment]
All icons requested in this issue have been added to the theme, except where there were issues.
Thank you to all involved.
