### ISSUE TITLE
Icon request: Lunarvim

### ISSUE THREAD

**Issue by bbhtt** [somepaulo/MoreWaita#100]
### Name of app

Lunarvim

### Link to official icon

https://raw.githubusercontent.com/LunarVim/LunarVim/15dc5292922b8b6009db645225bfee1f26796a68/utils/desktop/64x64/lvim.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

lvim

### Optional image of the app icon

N/A

### Additional context

N/A

**Comment by somepaulo** [comment]
Added

**Comment by bbhtt** [comment]
Thanks!
