### ISSUE TITLE
Icon request: Ryujinx

### ISSUE THREAD

**Issue by deusnovus** [somepaulo/MoreWaita#104]
### Name of app

Ryujinx

### Link to official icon

https://images.pcgamingwiki.com/0/07/Ryujinx_Logo.png

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

org.ryujinx.Ryujinx

### Optional image of the app icon

![Ryujinx_Logo](https://github.com/somepaulo/MoreWaita/assets/32219080/f20ab6d1-5a94-41ff-b56f-1abc96fc4c75)

### Additional context

Ryujinx is a Nintendo Switch emulator for Linux.

**Comment by somepaulo** [comment]
Done
