### ISSUE TITLE
Icon request: Portmaster

### ISSUE THREAD

**Issue by SharpStormGames** [somepaulo/MoreWaita#105]
### Name of app

Portmaster

### Link to official icon

https://github.com/safing/portmaster-ui/blob/develop/assets/icons/pm_light_256.png

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

portmaster

### Optional image of the app icon

![pm_light_256](https://github.com/somepaulo/MoreWaita/assets/112800647/5bd8f8f9-5741-4e0b-9676-55c15db7074c)

**Comment by somepaulo** [comment]
Done
