### ISSUE TITLE
Icon request: Julia

### ISSUE THREAD

**Issue by coxackie** [somepaulo/MoreWaita#106]
### Name of app

Julia

### Link to official icon

https://github.com/JuliaLang/julia

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

julia

### Optional image of the app icon

![image](https://github.com/somepaulo/MoreWaita/assets/22049642/77ec0ca8-c048-4389-9504-1778c10072c9)

### Additional context

The icon is the three dots making a triangle.

**Comment by somepaulo** [comment]
Done
