### ISSUE TITLE
Icon request: Texmaker

### ISSUE THREAD

**Issue by bbhtt** [somepaulo/MoreWaita#108]
### Name of app

Texmaker

### Link to official icon

See below

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

net.xm1math.Texmaker for flatpak, texmaker in the source code

### Optional image of the app icon

They don't have a browsable version of the source...

![texmaker](https://github.com/somepaulo/MoreWaita/assets/62639087/be4363d0-0648-44fc-b4e8-52e3da178d29)

### Additional context

n/a

**Comment by somepaulo** [comment]
Done
