### ISSUE TITLE
Icon request: Nheko

### ISSUE THREAD

**Issue by bbhtt** [somepaulo/MoreWaita#109]
### Name of app

Nheko

### Link to official icon

https://raw.githubusercontent.com/Nheko-Reborn/nheko/85556c9e10a3af8531ea5c19a46ebe56fc4aebf9/resources/nheko.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

im.nheko.Nheko

### Additional context

The desktop file just uses the app id as icon name https://github.com/Nheko-Reborn/nheko/blob/85556c9e10a3af8531ea5c19a46ebe56fc4aebf9/resources/nheko.desktop.in#L6

**Comment by somepaulo** [comment]
Done
