### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by dusansimic** [somepaulo/MoreWaita#11]
At some point, versions should be created so maintainers could create versioned packages for various distros (Fedora, Ubuntu, etc.) that don't usually have git packages like Arch Linux.

**Comment by somepaulo** [comment]
Yup, you're right. Will have to do releases.
I'll have them linked to adding batches of new icons and point releases for fixes.
I'll fix up the remaining flatpaks and other symlinks for existing icons and do a first release.

**Comment by somepaulo** [comment]
First release out

**Comment by dusansimic** [comment]
Great! I've already made a versioned package for the AUR this morning ([link](https://aur.archlinux.org/packages/morewaita)). I'm working on the rpm package now so I'll release it when it's done but I can't promise that it'll be today. For other distros, I don't usually make packages since I don't use them but anyone else is free to do so.

**Comment by somepaulo** [comment]
Excellent! Thank you for all your contributions! Added new link to readme.
