### ISSUE TITLE
Icon request: Waydroid

### ISSUE THREAD

**Issue by umahdroid** [somepaulo/MoreWaita#111]
### Name of app

Waydroid

### Link to official icon

https://github.com/waydroid/waydroid/blob/main/data/AppIcon.png

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

waydroid

**Comment by Tomoghno** [comment]
> ### Name of app
> 
> Waydroid
> ### Link to official icon
> 
> https://github.com/waydroid/waydroid/blob/main/data/AppIcon.png
> ### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)
> 
> waydroid
> ### Optional image of the app icon
> 
> _No response_
> ### Additional context
> 
> _No response_

but it already follows gnome's design guidelines

**Comment by somepaulo** [comment]
Done
