### ISSUE TITLE
Icon request: Firefox Nightly

### ISSUE THREAD

**Issue by nanopone** [somepaulo/MoreWaita#118]
### Name of app

Firefox Nightly

### Link to official icon

https://en.m.wikipedia.org/wiki/File:Firefox_Nightly_logo,_2019.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

org.mozilla.FirefoxNightly

**Comment by somepaulo** [comment]
Added
