### ISSUE TITLE
Icon request: LocalSend

### ISSUE THREAD

**Issue by fjbaldon** [somepaulo/MoreWaita#123]
### Name of app

LocalSend

### Link to official icon

https://github.com/localsend/localsend/blob/main/app/assets/img/logo-512.png

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

org.localsend.localsend_app

**Comment by wannafedor4** [comment]
![IMG_0135](https://github.com/somepaulo/MoreWaita/assets/151413500/b965be94-11fb-4f7b-8a1e-9382766ba501)
Quick mockup I made

**Comment by Red6785** [comment]
+1

**Comment by somepaulo** [comment]
Done
