### ISSUE TITLE
Icon request: Black Box (Terminal App)

### ISSUE THREAD

**Issue by ArcticDev78** [somepaulo/MoreWaita#128]
### Name of app

Black Box

### Link to official icon

https://gitlab.gnome.org/raggesilver/blackbox/-/raw/main/data/icons/hicolor/scalable/apps/com.raggesilver.BlackBox.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

com.raggesilver.BlackBox

### Optional image of the app icon

From the [Flathub page](https://flathub.org/apps/com.raggesilver.BlackBox):
![](https://dl.flathub.org/repo/appstream/x86_64/icons/128x128/com.raggesilver.BlackBox.png)

### Additional context

Link to the GitLab Repo of this app: https://gitlab.gnome.org/raggesilver/blackbox/
Link to the Flathub page of this app: https://flathub.org/apps/com.raggesilver.BlackBox

The current icon for this app on my GNOME desktop is the symbolic icon, but it doesn't seem to have a regular (scalable) icon. If this request is a duplicate, I apologize.

Thank you.

**Comment by somepaulo** [comment]
Black Box complies with Gnome's design guidelines, so I don't theme it. You should check your installation of Black Box to make sure all is in place. Your system should be using its original icon, the one in your issue. Could be Flatpak related though.
