### ISSUE TITLE
Move code to GitLab or Codeberg

### ISSUE THREAD

**Issue by julianfairfax** [somepaulo/MoreWaita#129]
It would be nice if the project's code were moved to GitLab or Codeberg. GitHub is not an open source platform, and being owned by Microsoft makes it more of a danger to open source projects, rather than a help.

**Comment by IdkWhatToCallMe123** [comment]
I would rather disagree.
More people use Github, which is a huge benefit as more people will discover this project. Also I personally way prefer Github's UI.
And it's not like Github has done anything to any project without actual reason.

**Comment by somepaulo** [comment]
Staying here for now.
