### ISSUE TITLE
Icon request: OpenBoard

### ISSUE THREAD

**Issue by julianfairfax** [somepaulo/MoreWaita#130]
### Name of app

OpenBoard

### Link to official icon

https://github.com/OpenBoard-org/OpenBoard/blob/master/resources/images/OpenBoard.png

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

ch.openboard.OpenBoard

### Optional image of the app icon

![](https://github.com/OpenBoard-org/OpenBoard/blob/master/resources/images/OpenBoard.png?raw=true)

**Comment by somepaulo** [comment]
Added
