### ISSUE TITLE
Icon request: LibreWolf

### ISSUE THREAD

**Issue by larouxn** [somepaulo/MoreWaita#131]
### Name of app

LibreWolf

### Link to official icon

https://repo.librewolf.net/librewolf.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

io.gitlab.librewolf-community

### Optional image of the app icon

![librewolf](https://github.com/somepaulo/MoreWaita/assets/1557529/8604ebd8-7cf8-42f4-94bd-c78c827f0803)

Produced a 1000x1000 PNG from the SVG linked above using GIMP.

### Additional context

[What is LibreWolf?](https://librewolf.net/#what-is-librewolf)

This project is a custom and independent version of Firefox, with the primary goals of privacy, security and user freedom.

LibreWolf is designed to increase protection against tracking and fingerprinting techniques, while also including a few security improvements. This is achieved through our privacy and security oriented settings and patches. LibreWolf also aims to remove all the telemetry, data collection and annoyances, as well as disabling anti-freedom features like DRM.

**Comment by yioannides** [comment]
@somepaulo Not sure if it's any help, but here you go (followed MoreWaita's dimensions and background gradient type): 

![librewolf](https://github.com/user-attachments/assets/7434e6d4-2f93-4a10-9e74-0e45cbb4084a)

flatpak ID: `io.gitlab.librewolf-community.svg`
