### ISSUE TITLE
Icon request: OpenToonz

### ISSUE THREAD

**Issue by notHaider** [somepaulo/MoreWaita#133]
### Name of app

OpenToonz

### Link to official icon

https://avatars.githubusercontent.com/u/15189838?s=200&v=4 i couldnt find a link on any other official site :(

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

io.github.OpenToonz (aur)

### Optional image of the app icon

![opentoonz](https://github.com/somepaulo/MoreWaita/assets/81862535/6b699995-643d-483e-8e89-6e6c3761ca25)

**Comment by somepaulo** [comment]
Done
