### ISSUE TITLE
Icon request: QGIS

### ISSUE THREAD

**Issue by linfindel** [somepaulo/MoreWaita#136]
### Name of app

QGIS

### Link to official icon

https://upload.wikimedia.org/wikipedia/commons/9/91/QGIS_logo_new.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

org.qgis.qgis

### Optional image of the app icon

![QGIS logo](https://upload.wikimedia.org/wikipedia/commons/9/91/QGIS_logo_new.svg)

**Comment by somepaulo** [comment]
Done
