### ISSUE TITLE
Icon request: MediathekView

### ISSUE THREAD

**Issue by julianfairfax** [somepaulo/MoreWaita#138]
### Name of app

MediathekView

### Link to official icon

https://github.com/mediathekview/MediathekView/blob/master/res/MediathekView.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

de.mediathekview.MediathekView

### Optional image of the app icon

![MediathekView](https://github.com/somepaulo/MoreWaita/assets/43753131/ec59bc83-ae55-464b-bbfb-e4b491e1a7f4)

**Comment by somepaulo** [comment]
Done
