### ISSUE TITLE
Icon request: ProtonMail Import-Export app

### ISSUE THREAD

**Issue by julianfairfax** [somepaulo/MoreWaita#139]
### Name of app

ProtonMail Import-Export app

### Link to official icon

https://github.com/ProtonMail/proton-bridge/blob/ie-1.3.3/internal/frontend/share/icons/ie.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

ch.protonmail.protonmail-import-export-app

### Optional image of the app icon

![ie](https://github.com/somepaulo/MoreWaita/assets/43753131/c2030e76-bb32-4056-ae24-2a31d7145fa4)

**Comment by somepaulo** [comment]
Done
