### ISSUE TITLE
Icon request: foot

### ISSUE THREAD

**Issue by wenjinnn** [somepaulo/MoreWaita#140]
### Name of app

foot

### Link to official icon

https://codeberg.org/dnkl/foot/media/branch/master/icons/hicolor/48x48/apps/foot.png

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

org.codeberg.dnkl.foot

### Optional image of the app icon

![foot](https://github.com/somepaulo/MoreWaita/assets/30885216/3fa76412-6472-41f3-995e-7b3db9b4c8c3)

**Comment by somepaulo** [comment]
Done
