### ISSUE TITLE
Icon request: Wireshark

### ISSUE THREAD

**Issue by rolo-g** [somepaulo/MoreWaita#142]
### Name of app

Wireshark

### Link to official icon

https://upload.wikimedia.org/wikipedia/commons/c/c6/Wireshark_icon_new.png

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

org.wireshark.Wireshark

### Additional context

For some strange reason in Fedora 39 on Gnome 45, there is a different icon when its pinned to the dash and when its in the app drawer:

Drawer: https://upload.wikimedia.org/wikipedia/commons/d/df/Wireshark_icon.svg

Dash: https://upload.wikimedia.org/wikipedia/commons/c/c6/Wireshark_icon_new.png

**Comment by somepaulo** [comment]
Done
