### ISSUE TITLE
Icon request: VIA

### ISSUE THREAD

**Issue by lmcj-xyz** [somepaulo/MoreWaita#144]
### Name of app

VIA

### Link to official icon

https://github.com/the-via/app/blob/main/src/assets/images/squarey.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

It does not provide a .desktop file.

### Optional image of the app icon

![squarey](https://github.com/somepaulo/MoreWaita/assets/47726645/9887d0ea-25b1-472e-bfad-534571c5a870)

### Additional context

VIA allows you to configure QMK/VIA  compatible keyboards.

To the extent I know, this doesn't have a desktop file associated, it's just an AppImage provided in the
[releases page](https://github.com/the-via/releases)
but they don't provide any other assets as far as I know.

I provide the one which seems to be the actual logo, but the following is another potential icon.

![Another potential icon](https://github.com/somepaulo/MoreWaita/assets/47726645/fd5d8b52-7af7-4bd4-8da0-97ded2523bfb)

**Comment by somepaulo** [comment]
Done
