### ISSUE TITLE
Icon request: DeaDBeeF

### ISSUE THREAD

**Issue by Kibbitzer** [somepaulo/MoreWaita#145]
### Name of app

DeaDBeeF

### Link to official icon

https://github.com/DeaDBeeF-Player/deadbeef/blob/master/icons/scalable/deadbeef.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

deadbeef

### Optional image of the app icon

The original icon is as follows:
![deadbeef](https://github.com/somepaulo/MoreWaita/assets/25698634/2d649d53-9cff-41c9-a655-3dee6471b08c)

This is a version I made myself to better fit with the Adwaita visual style:
![deadbeef-edited](https://github.com/somepaulo/MoreWaita/assets/25698634/04dc6b37-e375-46e1-9fd2-aea927bca7b6)

### Additional context

Feel free to use or modify my own proposition as I give up any and all ownership rights of it, for it is a derivative work from the original.

**Comment by somepaulo** [comment]
Done
