### ISSUE TITLE
Icon request: ClassiCube

### ISSUE THREAD

**Issue by sungsphinx** [somepaulo/MoreWaita#149]
### Name of app

ClassiCube

### Link to official icon

https://github.com/ClassiCube/ClassiCube/blob/master/misc/linux/flatpak/net.classicube.flatpak.client.svg or https://github.com/ClassiCube/ClassiCube/blob/master/misc/CCicon.png

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

Flatpak: net.classicube.flatpak.client

### Additional context

Normal builds of ClassiCube for Linux (non-flatpak) do not include a desktop entry out of the box, there [is a script that sets one up](https://github.com/ClassiCube/ClassiCube/blob/master/misc/linux/install-desktop-entry.sh), but the icon links directly to a PNG that the script downloads in your current directory.

**Comment by somepaulo** [comment]
Done
