### ISSUE TITLE
Icon request: CSV (& TSV etc.) files mime

### ISSUE THREAD

**Issue by erlefloch** [somepaulo/MoreWaita#152]
### Name of app

any text file that stores tabular data: CSV, TSV etc.

### Link to official icon

none

**Comment by somepaulo** [comment]
Done for `.csv` files. Couldn't find any specs for `.tsv`. If you find this is not covering all you had in mind, feel free to reopen adding the missing file type from its properties (in Nautilus).

**Comment by erlefloch** [comment]
Thanks ! It says "text/tab-separated-values"


![TSV_screenshot](https://github.com/user-attachments/assets/593f5305-dd9e-4b17-8da6-02d2327cf2cf)

**Comment by somepaulo** [comment]
Added that too.

**Comment by erlefloch** [comment]
Thanks!
