### ISSUE TITLE
Pamac icon is the same as Gnome Software

### ISSUE THREAD

**Issue by fabrixx** [somepaulo/MoreWaita#153]
In Adwaita the pamac icon is similar to an open cardboard box, in MoreWaita it is the same as that of Gnome Software, I have both icons in the dash and I'm getting confused now.

![icone](https://github.com/somepaulo/MoreWaita/assets/1190942/864bedca-4ea9-4a47-8ae0-80dd638567f2)

**Comment by somepaulo** [comment]
Yup. Pamac doesn't use its own icon (available in MoreWaita), it uses the `system-software-install` icon instead, which happens to be the icon Gnome Software uses too. This can't be overridden from within an icon theme. Only a manual override of the icon name to `pamac` in your `/usr/share/applications/org.manjaro.pamac.manager.desktop` and/or `/usr/share/applications/pamac-installer.desktop` can help. Either copy these two files to your `~/.local/share/applications/` folder and edit them there, or use a GUI like `menulibre` or `libre-menu-editor`.

**Comment by fabrixx** [comment]
But why if I uninstall Morewaita the icon becomes that of an open brown box? Now I can't put an image because I'm out but if you want I can do it later
