### ISSUE TITLE
Icon request: NetBeans

### ISSUE THREAD

**Issue by fjbaldon** [somepaulo/MoreWaita#155]
### Name of app

NetBeans

### Link to official icon

https://netbeans.apache.org/_/images/apache-netbeans.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

org.apache.netbeans

### Optional image of the app icon

![netbeans](https://github.com/somepaulo/MoreWaita/assets/114366108/b4bd05fc-8598-4c18-9609-4218ff1a1ee4)

**Comment by somepaulo** [comment]
Done
