### ISSUE TITLE
Icon request: Logseq

### ISSUE THREAD

**Issue by lmcj-xyz** [somepaulo/MoreWaita#156]
### Name of app

Logseq

### Link to official icon

https://github.com/logseq/logseq/blob/master/resources/icons/logseq_big_sur.png

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

com.logseq.Logseq

### Optional image of the app icon

![logseq](https://github.com/somepaulo/MoreWaita/assets/47726645/618ba3e5-e8d0-4a6e-b681-655355e1e5a4)

### Additional context

The official download is an AppImage, so I would imagine just `logseq` for the icon name would do?

**Comment by somepaulo** [comment]
Added
