### ISSUE TITLE
Icon request: AppFlowy

### ISSUE THREAD

**Issue by AxelSkye** [somepaulo/MoreWaita#157]
### Name of app

AppFlowy

### Link to official icon

https://raw.githubusercontent.com/AppFlowy-IO/AppFlowy/fdaca36b87ffb8f4035121bcdebe6c1fab4bcda1/frontend/resources/flowy_icons/40x/flowy_logo.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

io.appflowy.AppFlowy

### Optional image of the app icon

![flowy_logo](https://github.com/somepaulo/MoreWaita/assets/31951244/019e04ef-1ef3-464a-b0ce-41fc8e2fd91f)

**Comment by somepaulo** [comment]
Done
