### ISSUE TITLE
Some icon missing in GNOME 46 & GTK 4 with Libadwaita apps

### ISSUE THREAD

**Issue by Anifyuli** [somepaulo/MoreWaita#158]
Hello Mister, I want to show you some small bugs in this icon theme. If I applied this icon, I get missing icon in some apps, especially Foliate. I still haven't idea how this happened. You can see this pics.
![image](https://github.com/somepaulo/MoreWaita/assets/73734843/b0f17b99-3f2a-4452-8af9-1a4bfbc302b9)

If I apply Adwaita icon, it can show properly, like this screenshot
![image](https://github.com/somepaulo/MoreWaita/assets/73734843/0a172474-88dc-4ca5-a797-1fd923117ef8)

I wish this project still well maintained & get updates for new icons. Thanks for read my issue & sorry my English

System info : 
Distro : NixOS unstable channel
GNOME shell version : 46.2
Install source : [nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/mo/morewaita-icon-theme/package.nix#L35)

**Comment by azrdn** [comment]
Hi @Anifyuli, i think this might be related : https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/3699

**Comment by Anifyuli** [comment]
I think it is a related issue too. I wish it could be fixed

**Comment by azrdn** [comment]
There is a workaround mentioned there involving moving the icon pack to /usr/share/icons
but since you're using NixOs and its immutable, i don't really know how to apply it, you might be able to figure it out

personally i tried this icon pack and there is no missing icons

**Comment by Anifyuli** [comment]
> There is a workaround mentioned there involving moving the icon pack to /usr/share/icons but since you're using NixOs and its immutable, i don't really know how to apply it, you might be able to figure it out

I apply some workaround to symlink this icon to `/usr/share/icons` because my Flatpak app can't access it without this workaround. You can check in [here](https://github.com/Anifyuli/my-nixos/blob/main/programs/desktop.nix)
