### ISSUE TITLE
Icon request: Zed

### ISSUE THREAD

**Issue by reesericci** [somepaulo/MoreWaita#159]
### Name of app

Zed

### Link to official icon

https://zed.dev/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fapp-logo2.9b5f959f.png&w=640&q=75

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

/var/home/reesericci/.local/zed.app/share/icons/hicolor/512x512/apps/zed.png, dev.zed.Zed

### Optional image of the app icon

![image](https://github.com/somepaulo/MoreWaita/assets/19589006/99b41c80-6801-45df-9f89-843733ff9982)

### Additional context

Zed is a new code editor that just released for Linux (or as I've recently taking to calling it, GNU + Linux :P), and I'd love to see an Adwaita-style icon!

**Comment by somepaulo** [comment]
Added
