### ISSUE TITLE
Broken mimetype: `.pub`

### ISSUE THREAD

**Issue by fiftydinar** [somepaulo/MoreWaita#160]
It started happening very recently, don't know when

**Comment by iaacornus** [comment]
hi, is this still notable from the current version?

**Comment by fiftydinar** [comment]
> hi, is this still notable from the current version?

 @iaacornus
 Yes (I use git version, which had the last update 5 months ago).

**Comment by iaacornus** [comment]
can you upload a screenshot so we can see how it looks like in your system and can confirm if I managed reproduce it on my system

**Comment by fiftydinar** [comment]
@iaacornus It looks like this:
![Screenshot from 2024-09-19 08-16-58](https://github.com/user-attachments/assets/468515b9-6b46-4adc-b44b-b74f5e56aa33)

While it should looks like this:
https://github.com/somepaulo/MoreWaita/blob/0f4ed19f51b5ca8f0622c9e154886efb2a5ff59b/mimes/scalable/application-pgp-keys.svg

**Comment by iaacornus** [comment]
can you send the output of `file cosign.pub`? In my system it seems more like a gnome/de error, it is being recognized as microsoft publisher file instead of gpg/pub:

![image](https://github.com/user-attachments/assets/bbecb0d0-67be-4300-8f3c-8e1c7ac32abb)
```
iaacornus@sysmain ~ [1]> file my_key.pub
my_key.pub: OpenPGP Public Key Version 4, Created Mon Sep 16 03:25:48 2024, RSA (Encrypt or Sign, 4096 bits); User ID; Signature; OpenPGP Certificate
```

**Comment by fiftydinar** [comment]
@iaacornus

![image](https://github.com/user-attachments/assets/551600b2-f408-47e4-af06-d095c7820431)

`file` doesn't seem to properly work here, cuz it outputs this:
```
file cosign.pub

cosign.pub: ASCII text
```

It seems like you're right, it's an upstream issue.

**Comment by iaacornus** [comment]
> @iaacornus
> 
> ![image](https://private-user-images.githubusercontent.com/65243233/368870414-551600b2-f408-47e4-af06-d095c7820431.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3Mjg0NTgsIm5iZiI6MTcyNjcyODE1OCwicGF0aCI6Ii82NTI0MzIzMy8zNjg4NzA0MTQtNTUxNjAwYjItZjQwOC00N2U0LWFmMDYtZDA5NWM3ODIwNDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA2NDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlYWJlYTk2MWY2YWEwYWQ2Y2E1ZGI1ZThlOWVjOWQ3YmMwNGZkNTgyZmNkZWM4MDhiYzI3OGY1MWNjYTJiMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ecie8Cyb5t0c1-xVBixOeRVXA-Y_h9xFE06OUcx6cAA)
> 
> `file` doesn't seem to properly work here, cuz it outputs this:
> 
> ```
> file cosign.pub
> 
> cosign.pub: ASCII text
> ```
> 
> It seems like you're right, it's an upstream issue.

yeah, it's unfortunate that those 2 conflicts, but if you don't use microsoft publisher, you can disable/override that and use the pgp icon for all .pub files.

**Comment by somepaulo** [comment]
Which extension corresponds to which file type is defined by the system mimetypes list, so mimetype icons work by applying to a mimetype, not the file extension.
