### ISSUE TITLE
[CONTRIBUTION] MIME icon for Bitwig Studio: `.bwproject` `.bwpreset` `.bwclip`

### ISSUE THREAD

**Issue by yioannides** [somepaulo/MoreWaita#161]
Hi, I would like to contribute a MIME icon associated with Bitwig Studio file types: `.bwproject` `.bwpreset` `.bwclip` (EDIT: and `.multisample`)

I don't know how to specifically merge MIME icons onto the master branch, so here is the icon in plain .svg:

![application-x-bitwig](https://github.com/user-attachments/assets/bf6c57c3-0f61-4b1d-90e8-586d85b7f9f4)

**Comment by iaacornus** [comment]
Hi. I'm not a contributor/maintainer of the project. But you should open a merge request for review so it can be included in the future releases
