### ISSUE TITLE
New default Zotero (version 7) icon is good looking, replace the current MoreWaita icon

### ISSUE THREAD

**Issue by nbCloud91** [somepaulo/MoreWaita#162]
The new refurbished icon for Zotero7 fits quite nicely with the Adwaita theme, maybe there is no need to have the MoreWaita supplied icon for Zotero?

This is the new default icon:
![image](https://github.com/user-attachments/assets/dc9e90d5-9006-4629-89f0-70673e78e8d5)

This one is the one provided by MoreWaita currently:
![image](https://github.com/user-attachments/assets/7a74628c-c844-4fb6-950f-dd9ea8af0a14)

**Comment by somepaulo** [comment]
The Zotero icon has now been removed from the theme in the git version.
