### ISSUE TITLE
Icon request: Zen Browser

### ISSUE THREAD

**Issue by lorebored** [somepaulo/MoreWaita#163]
### Name of app

Zen Browser

### Link to official icon

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-Q-PnqUokfz85I1InZ4i5brzG-iditlUaBA&s

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

io.github.zen_browser.zen

**Comment by federicotorrielli** [comment]
+1 to this, looking forward!
