### ISSUE TITLE
Made in icon: folder-temp

### ISSUE THREAD

**Issue by TecCheck** [somepaulo/MoreWaita#167]
Hi there, I made (or rather put together) an icon:

![folder-temp](https://github.com/user-attachments/assets/be246be8-d7e0-4c8f-8115-eec02466b126)

I was too lazy to open a pull request, but if I should do that, please tell me. Hope this makes it into MoreWaita because I think it's a great project. Thanks :)

**Comment by iaacornus** [comment]
I'm not a contributor/maintainer of the project. But yes, if you want this to be included, you should open a merge request.

**Comment by iaacornus** [comment]
hi can you open a mr of this in the fork [Morewaita-Dev/MoreWaita](https://github.com/MoreWaita-Dev/MoreWaita)?

**Comment by TecCheck** [comment]
For sure. Thank you

**Comment by somepaulo** [comment]
Thank you!
No need to open a pull request unless you also want to do the legacy folder. I'll add the folder in v47 coming up in a couple of weeks (should be in git sooner though).

**Comment by somepaulo** [comment]
Done. With legacy folder and symbolic icon.
