### ISSUE TITLE
Proton vpn icon does not apply

### ISSUE THREAD

**Issue by dexterdy** [somepaulo/MoreWaita#170]
I saw that the theme includes a protonvpn icon, but it does not seem to apply. Gnome still shows the old default icon. I checked the desktop file, the name of  the icon is proton-vpn-logo. I created a new symlink in the theme from proton-vpn-logo.svg to your icon, but that does not seem to work for whatever reason.

**Comment by dexterdy** [comment]
oh updating icon-theme.cache resolves the issue. 

I probably shouldn't close this issue, because the missing symlink is still an issue that I resolved manually

**Comment by somepaulo** [comment]
Thanks for spotting that. Pushed new symlink to git.
