### ISSUE TITLE
Icon request: Betterbird

### ISSUE THREAD

**Issue by federicotorrielli** [somepaulo/MoreWaita#172]
### Name of app

Betterbird

### Link to official icon

https://www.betterbird.eu/betterbird.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

eu.betterbird.Betterbird

source: https://raw.githubusercontent.com/Betterbird/thunderbird-patches/main/metadata/eu.betterbird.Betterbird.desktop

**Comment by yioannides** [comment]
You provided the wrong info for Betterbird

**Comment by federicotorrielli** [comment]
> You provided the wrong info for Betterbird

My bad, I've corrected the mistakes. I was tired from work :)

**Comment by somepaulo** [comment]
Done
