### ISSUE TITLE
Icon request: KiCad

### ISSUE THREAD

**Issue by hasecilu** [somepaulo/MoreWaita#178]
### Name of app

KiCad

### Link to official icon

https://gitlab.com/kicad/code/kicad/-/tree/master/resources/linux/icons/hicolor/scalable/apps?ref_type=heads

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

kicad

### Optional image of the app icon

![image](https://github.com/user-attachments/assets/21516320-f4d8-4bc2-a3a4-f4d4dbbf5a92)

### Additional context

The MIME icons are really good (https://gitlab.com/kicad/code/kicad/-/tree/master/resources/linux/icons/hicolor/scalable/mimetypes?ref_type=heads) and I think the icons of the different applications fit the style so I would be only interested on the custom folder icon.

**Comment by somepaulo** [comment]
Done
