### ISSUE TITLE
Any way to theme these?

### ISSUE THREAD

**Issue by julianfairfax** [somepaulo/MoreWaita#18]
Icons in the about section of Inkscape and the GIMP beta

![image](https://user-images.githubusercontent.com/43753131/202545797-329d6bae-4c55-4d44-a2a2-4c39896f9ea7.png)

![Screenshot from 2022-11-17 20-55-31](https://user-images.githubusercontent.com/43753131/202546026-b74c1a38-c9ce-4ba6-b7ac-5a44fa5c1524.png)

**Comment by somepaulo** [comment]
Both are part of the respective program's internal graphics.
The Inkscape one is in `/usr/share/inkscape/screens/about.svg`.
The Gimp one is in `/usr/share/gimp/2.0/images/gimp-logo.png` and `/usr/share/gimp/2.0/images/wilber.png`.
There's no way to override those through an icon theme, AFAIK.
Reopen this issue if you discover a solution.
