### ISSUE TITLE
Icon request: Arduino

### ISSUE THREAD

**Issue by hasecilu** [somepaulo/MoreWaita#180]
### Name of app

Arduino

### Link to official icon

https://commons.wikimedia.org/wiki/File:Arduino_Logo.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

arduino-ide

### Optional image of the app icon

![](https://camo.githubusercontent.com/ce8e24961efdbc60172a84d263e42deb2ff9b48514a370ed64bdd7f9a96af5ff/687474703a2f2f636f6e74656e742e61726475696e6f2e63632f6272616e642f61726475696e6f2d636f6c6f722e737667)

### Additional context

Not sure is this really applies because the MIME type is recognized as C code and this, it uses C icon, not sure if current app theme needs changes. I open this to submit the folder icon.

**Comment by somepaulo** [comment]
Done
