### ISSUE TITLE
Inkscape icon looks to dark

### ISSUE THREAD

**Issue by Anifyuli** [somepaulo/MoreWaita#19]
Hello mister.
I have a little advice for your icon, especially Inkscape
Inkscape icon looks too dark on dark wallpaper and it's not good for visibility. I wish Inkscape icon can to change to grey or dark grey, not black. You can get my point in this screenshot
![Screenshot from 2022-11-29 08-03-17](https://user-images.githubusercontent.com/73734843/204413477-fafcc003-072f-45a3-acb1-b653a20fff3c.png)

I hope you can fix it. Thanks, Mister. Sorry my English

**Comment by somepaulo** [comment]
That's the problem with Inkscape's branding.
MoreWaita skicks to original brand colours.
Still, I'll think about a way to make the icon more visible. It's not a priority for now though.

**Comment by somepaulo** [comment]
I gave it a lighter side to make it stand out. That's about as much as I can do without modifying the original colour, which I won't do.
Please reopen issue if you have different suggestions for Inkscape that do not involve changing its main colour.
