### ISSUE TITLE
Add installation guide in the README

### ISSUE THREAD

**Issue by anmolmathias** [somepaulo/MoreWaita#2]
For a little accessibility, just a little git clone and copy to icons folder disclaimer should do

**Comment by dusansimic** [comment]
I'd recommend adding meson for more standardized installation method. That would also make it easier for package maintainers to work with the project.

**Comment by somepaulo** [comment]
> I'd recommend adding meson

How do I do that?

**Comment by dusansimic** [comment]
> How do I do that?

I'd recommend starting from the [Meson Build System documentation page](https://mesonbuild.com/Manual.html) (even tho it's a build system, it's fantastic for installing various files). You could also take a look at some other GNOME projects that use it how they manage meson configs.

I could work on adding meson if I find some free time in the following days.

**Comment by somepaulo** [comment]
> I could work on adding meson if I find some free time

That would be great. I don't think I'm ready to dive into this just yet. Too busy atm.

**Comment by somepaulo** [comment]
> a little git clone and copy to icons folder

That's done now.
