### ISSUE TITLE
Icon request: Sioyek

### ISSUE THREAD

**Issue by lmcj-xyz** [somepaulo/MoreWaita#210]
### Name of app

Sioyek

### Link to official icon

https://github.com/ahrm/sioyek/blob/main/resources/sioyek-icon-linux.png

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

sioyek-icon-linux

### Optional image of the app icon

![sioyek-icon-linux](https://github.com/user-attachments/assets/c9082793-f4a1-4e37-a3f3-36a579f97cf1)

### Additional context

The information provided is for the official release as an AppImage. There is a Flatpak version that is not official, that one may handle it differently.

**Comment by somepaulo** [comment]
Done
