### ISSUE TITLE
Icon request: pycharm community

### ISSUE THREAD

**Issue by CodedIsTaken** [somepaulo/MoreWaita#214]
### Name of app

pycharm community.

### Link to official icon

https://en.wikipedia.org/wiki/File:PyCharm_Icon.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

?

### Additional context

i use the copr repo for pycharm-community, might not be supported.

**Comment by yioannides** [comment]
It already exists : https://github.com/somepaulo/MoreWaita/blob/ff2bc0d1cff5e8215db92edbf0b9276736dd14cd/scalable/apps/pycharm.svg

**Comment by somepaulo** [comment]
What does the `pycharm.desktop` file (the actual name may be different, but should include `pycharm` and have a `.desktop` extension) on your system say on the `Icon` line?

**Comment by somepaulo** [comment]
Added new symlinks for PyCharm that should hopefully fix theming for more distros.
