### ISSUE TITLE
Icon request: Emacs

### ISSUE THREAD

**Issue by wroyca** [somepaulo/MoreWaita#218]
### Name of app

Emacs

### Link to official icon

  <img src="https://upload.wikimedia.org/wikipedia/commons/0/08/EmacsIcon.svg" width="128" height="128">

https://upload.wikimedia.org/wikipedia/commons/0/08/EmacsIcon.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

emacs

### Additional context

Morewaita has an Emacs folder, but no Emacs icon to go by. :)

**Comment by somepaulo** [comment]
Done
