### ISSUE TITLE
Icon request: LazPaint

### ISSUE THREAD

**Issue by vmaskmovps** [somepaulo/MoreWaita#221]
### Name of app

LazPaint

### Link to official icon

https://lazpaint.github.io/img/lazpaint_icon.png

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

lazpaint

### Optional image of the app icon

![image](https://github.com/user-attachments/assets/d4803a80-88af-46ef-b2c0-bfdfc5588d8a)

### Additional context

You can find all sizes here (16x16 to 2048x2048): https://github.com/bgrabitmap/lazpaint/tree/master/resources/icon. The closest icons would be Krita and KolourPaint, and to a lesser extent GIMP's brush.

**Comment by somepaulo** [comment]
This one will be tricky. I'll see what I can do about it.

**Comment by somepaulo** [comment]
Done
