### ISSUE TITLE
Icon request: CudaText

### ISSUE THREAD

**Issue by vmaskmovps** [somepaulo/MoreWaita#222]
### Name of app

CudaText

### Link to official icon

https://github.com/Alexey-T/CudaText/raw/refs/heads/master/app_res/icon_source/cudatext_v2_gimp.xcf

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

cudatext-512

### Optional image of the app icon

Frustratingly enough, the source is a GIMP file. Here's the PNG version (1024 x 1024):
![cudatext_v2_gimp](https://github.com/user-attachments/assets/d56ae787-5bef-4cd4-a650-7a81d57515e6)

### Additional context

CudaText has a Flatpak version too: https://github.com/flathub/io.github.cudatext.CudaText-Qt/

I've been reading the yml file, and I can't exactly see what's the icon name in this case. I believe `cudatext-512` should apply for the Flatpak version too, but it also references `io.github.cudatext.CudaText-Qt`.

**Comment by somepaulo** [comment]
Yup, flatpak icons follow the flatpak app naming conventions. What you provided should be enough. I'm working on requests oldest to newest. Should get to this in a couple of weeks tops.
