### ISSUE TITLE
Icon request: GIMP (3.0 variant)

### ISSUE THREAD

**Issue by GittyMac** [somepaulo/MoreWaita#228]
### Name of app

GIMP

### Link to official icon

https://www.gimp.org/news/2024/11/06/gimp-3-0-RC1-released/gimp-logo.png

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

org.gimp.GIMP

### Optional image of the app icon

![image](https://github.com/user-attachments/assets/92138eb9-f175-4517-92ef-bc2540a2ac78)

### Additional context

In GIMP 3, a [redesigned Wilber icon](https://gitlab.gnome.org/GNOME/gimp-data/-/blob/main/images/logo/README.md) was created to replace the old one.

**Comment by somepaulo** [comment]
Man, you're quick. I barely finished reading about it when you opened this ))  
Working on requests older to newer. Will def redo GIMP.

**Comment by somepaulo** [comment]
Done
