### ISSUE TITLE
How do i use the folder icons?

### ISSUE THREAD

**Issue by im-viriv** [somepaulo/MoreWaita#23]
How would i go about using the folder icons? I thought name folders or them having a git file in there would do the trick but they don't get assigned the folder icon automatically. Do i need to do something on my end?

**Comment by fawaz006** [comment]
Just go to the properties, then click on the folder icon and choose the [image](https://raw.githubusercontent.com/somepaulo/MoreWaita/main/places/scalable/folder-git.svg).
Easy right 👍
![image](https://user-images.githubusercontent.com/93544997/206901914-8e3ef7ce-6cfd-4fd0-b156-5011af86614e.png)
