### ISSUE TITLE
Icon request: Zen Browser

### ISSUE THREAD

**Issue by dpejoh** [somepaulo/MoreWaita#239]
### Name of app, mime type or folder

Zen Browser

### Link to official icon

https://zen-browser.app/

### Name of icon as referenced in the .desktop file (Flatpak and AppImage apps' icon names often differ from regular ones for the same app).

zen

### Optional image of the icon

https://zen-browser.app/branding-assets

**Comment by somepaulo** [comment]
Does [this](https://github.com/somepaulo/MoreWaita/blob/main/scalable/apps/zen-browser.svg) not work for you?

**Comment by dpejoh** [comment]
Sorry it's my fault, I have the portable version, so the problem is in my .desktop file and icon location
