### ISSUE TITLE
[Icon request] GeoGebra

### ISSUE THREAD

**Issue by julianfairfax** [somepaulo/MoreWaita#24]
An icon for GeoGebra would be nice!

Icon: https://commons.wikimedia.org/wiki/File:Geogebra.svg
Icon name: org.geogebra.GeoGebra
Flatpak name: org.geogebra.GeoGebra

You should add an issue template for icon requests

**Comment by dusansimic** [comment]
I agree about the issue template, that would make it easier for users to submit new requests and format them in an expected way while giving the maintainer and contributors all the necessary information to make an icon.

It would also give a thread where design proposals could be discussed. So far, there hasn't been a review process for the icons, it's mostly just that if an icon is submitted, it's merged. I think there is some room for changes on some icons and a discussion would be useful.

**Comment by somepaulo** [comment]
Done
