### ISSUE TITLE
Icon request: Raspberry Pi Imager

### ISSUE THREAD

**Issue by thtrf** [somepaulo/MoreWaita#249]
### Name of app, mime type or folder

Raspberry Pi Imager

### Link to official icon

https://github.com/raspberrypi/rpi-imager/blob/qml/src/icons/rpi-imager.ico

### Name of icon as referenced in the .desktop file (Flatpak and AppImage apps' icon names often differ from regular ones for the same app).

org.raspberrypi.rpi-imager

### Optional image of the icon

![image](https://github.com/user-attachments/assets/5dd9ca6d-7cd7-49d5-a1cf-747f52fddb01)

**Comment by somepaulo** [comment]
Done
