### ISSUE TITLE
Colors are too loud and icons are too flat for some apps, imho

### ISSUE THREAD

**Issue by developer91234** [somepaulo/MoreWaita#25]
A lot of icons don't really look in keeping with Gnome's theme.

**Comment by dusansimic** [comment]
What are the examples of those icons that you thing don't conform to GNOMEs design language?

**Comment by somepaulo** [comment]
The concept of this theme is to mimic Adwaita icons for third-party apps while staying as close as possible to the original icons, and that includes preserving brand colours.

Not an issue. Won't fix.
