### ISSUE TITLE
Icon request: BlueBubbles

### ISSUE THREAD

**Issue by THZ-GH** [somepaulo/MoreWaita#250]
### Name of app, mime type or folder

BlueBubbles

### Link to official icon

https://github.com/BlueBubblesApp/bluebubbles-app/blob/master/assets/icon/icon.png

### Name of icon as referenced in the .desktop file (Flatpak and AppImage apps' icon names often differ from regular ones for the same app).

app.bluebubbles.BlueBubbles

### Optional image of the icon

![image](https://github.com/user-attachments/assets/77fd47df-9191-4afa-8c64-8df3db2a463d)

### Additional context

This is for the client app for any platform, as opposed to the server app only for macOS.

**Comment by somepaulo** [comment]
Done
