### ISSUE TITLE
Icon request: Jellyfin Media Player

### ISSUE THREAD

**Issue by nattadasu** [somepaulo/MoreWaita#251]
### Name of app, mime type or folder

Jellyfin Media Player

### Link to official icon

https://github.com/jellyfin/jellyfin-ux/blob/master/branding/SVG/icon-transparent.svg

### Name of icon as referenced in the .desktop file (Flatpak and AppImage apps' icon names often differ from regular ones for the same app).

com.github.iwalton3.jellyfin-media-player

### Additional context

The icon is directly derived without any modification. If possible, it'd be nice if there's a symbolic icons for Jellyfin server itself, as I used it on a system tray for status monitoring.

**Comment by somepaulo** [comment]
Done
