### ISSUE TITLE
Icon request: Zen Browser (New icon)

### ISSUE THREAD

**Issue by lorebored** [somepaulo/MoreWaita#253]
### Name of app, mime type or folder

Zen Browser

### Link to official icon

https://flathub.org/_next/image?url=https%3A%2F%2Fdl.flathub.org%2Fmedia%2Fio%2Fgithub%2Fzen_browser.zen%2Ff8cf322f3227e3dd61c2098028702639%2Ficons%2F128x128%2Fio.github.zen_browser.zen.png&w=128&q=100

### Name of icon as referenced in the .desktop file (Flatpak and AppImage apps' icon names often differ from regular ones for the same app).

zen

### Optional image of the icon

![io(1)](https://github.com/user-attachments/assets/3abc7010-1f0a-4626-8af5-a21f288bf209)

**Comment by lorebored** [comment]
the link download the icon automatically, here is the flathub page where you can se the image without downloading it 
https://flathub.org/apps/io.github.zen_browser.zen

**Comment by somepaulo** [comment]
Done
