### ISSUE TITLE
Add category and legacy icons.

### ISSUE THREAD

**Issue by Initu-Castilhos** [somepaulo/MoreWaita#255]
I know that MoreWaita is designed only for the GNOME desktop, but it would be nice to use MoreWaita on other desktops like Cinnamon, Budgie, XFCE, etc... since from Adwaita 42 the legacy icons were removed. AdwaitaLegacy was created for Adwaita to inherit, but it is inconsistent mixing symbolic and colored icons and also the size is limited to 48px. Category icons can be symbolic like in Numix.

**Comment by Initu-Castilhos** [comment]
I can collect the missing icons in a .zip file for you to analyze right here, as I don't know how to create one on guithub, is that okay?

**Comment by somepaulo** [comment]
That could help. Especially if you keep the folder structure for easy comparison in search of possible duplicates.

**Comment by Initu-Castilhos** [comment]
[
[Morewaita-plus.zip](https://github.com/user-attachments/files/18218827/Morewaita-plus.zip)
](url)

**Comment by Initu-Castilhos** [comment]
[Morewaita-plus.zip](https://github.com/user-attachments/files/18218845/Morewaita-plus.zip)

**Comment by somepaulo** [comment]
Obrigado. Vou ver o que se pode fazer sem causar problemas em Gnome.

**Comment by somepaulo** [comment]
All legacy icons added.  
Some of these exist already as symbolic in Adwaita/AdwaitaLegacy. I haven't seen any interference, but if full-colour icons start cropping out instead of symbolic ones in Gnome, I'll have to kill off the full-colour ones.
Please post separate issues if anything's wrong.
