### ISSUE TITLE
[Icon Request] Obsidian icon

### ISSUE THREAD

**Issue by voedev** [somepaulo/MoreWaita#26]
# Icon Request

* Icon name: [Obsidian](https://obsidian.md/)
* Screenshots of similar icons:
* Download icon: https://obsidian.md/blog/new-obsidian-icon/

![Untitled-3](https://github.com/somepaulo/MoreWaita/assets/42519520/f5c8a39a-0e5b-4abe-a325-f9973c442a9f)

**Comment by voedev** [comment]
Hey @somepaulo! I thought it would be cool if you could add an Obsidian icon to the MoreWaita pack.

**Comment by lmcj-xyz** [comment]
A new icon for Obsidian has been released, see [this blog post](https://obsidian.md/blog/new-obsidian-icon/).

**Comment by voedev** [comment]
> A new icon for Obsidian has been released, see [this blog post](https://obsidian.md/blog/new-obsidian-icon/).

Thanks, i've update icon request

**Comment by deusnovus** [comment]
+1 on that Obsidian icon request.

**Comment by somepaulo** [comment]
Added
