### ISSUE TITLE
Icon request: Dropbox

### ISSUE THREAD

**Issue by MarvinDjd** [somepaulo/MoreWaita#262]
### Name of app, mime type or folder

Dropbox

### Link to official icon

https://de.wikipedia.org/wiki/Dropbox#/media/Datei:Dropbox_logo_2017.svg

### Name of icon as referenced in the .desktop file (Flatpak and AppImage apps' icon names often differ from regular ones for the same app).

python3-dropbox-12.0.2-3.fc41.noarch

### Optional image of the icon

![OIP](https://github.com/user-attachments/assets/0a95bb45-df6b-4d79-84f1-b222751a675b)

### Additional context

There are still those old light blue icons floating around, hardly the new one in any icon set.

**Comment by somepaulo** [comment]
What's the actual icon name you have on your system?

**Comment by yioannides** [comment]
Not sure whether OP is referring to the headless package or the `nautilus-dropbox` package, but the Dropbox Linux package is a weird one: it's a shell script installed via CLI, does not launch in the Dock, auto-launches during boot, runs in the background in the system tray and the icon itself is only seen via Overview.

The icon name is just `dropbox`, as found on its .desktop file: `Icon=dropbox`

**Comment by MarvinDjd** [comment]
Yes I meant the headless package and couldn´t find the icon-name as described. Nautilus has a folder icon so it´s great.
