### ISSUE TITLE
Preferences-desktop and cinnamon-virtual-keyboard icons are not colored.

### ISSUE THREAD

**Issue by Initu-Castilhos** [somepaulo/MoreWaita#264]
First of all, thank you very much for adding the icons I asked you to and for the beautiful work, it was great. There are only 2 problems: the preferences-desktop and cinnamon virtual-keyboard icons were not colored as shown in the image below:
![Screenshot from 2024-12-29 04-32-02](https://github.com/user-attachments/assets/efdfa453-2834-4bc6-84d2-7c0ccdcdf017)
![Screenshot from 2024-12-29 04-32-50](https://github.com/user-attachments/assets/607eb0bd-2d58-452e-b583-7dc75e7e2bad)

To solve the preferences-desktop icon problem, you have to rename the icon to preferences-desktop-symbolic in the symbolic folder:
![Screenshot from 2024-12-29 04-52-12](https://github.com/user-attachments/assets/005de481-bf89-4837-968d-6f7f51ea8c21)

The cinnamon-virtual-keyboard icon has to be added to the scalable/devices description in the index/theme file.
![Screenshot from 2024-12-29 04-52-51](https://github.com/user-attachments/assets/bd37783a-e3eb-4cb4-81ee-be78172936f3)

Congratulations on the beautiful work.

**Comment by somepaulo** [comment]
Should be fixed now
