### ISSUE TITLE
Icon request: Symbolic legacy categories

### ISSUE THREAD

**Issue by Eggmanplant** [somepaulo/MoreWaita#266]
I'd like to have symbolic versions of legacy categories for ArcMenu and LibreMenuEditor. Only a symbolic icon for Accessories exists and it is in stock Adwaita.

Also, the lines from the ruler thing on the Accessories app icon are looking non-Adwaita-y. The Accessories app icon is a modified app icon of the app Cambalache. Why not use this icon also for Cambalache? Cambalache's Flatpak App ID/Icon is ar.xjuan.Cambalache. There is no native version of Cambalache.

**Comment by somepaulo** [comment]
There are currently 11 category icons in MoreWaita. Six of them (accessories, development, education, internet, office, and other) have symbolic icons in MoreWaita. The other five (games, graphics, multimedia, science, and system) are catered for by Adwaita itself (which MoreWaita depends on). They're in `/usr/share/icons/Adwaita/symbolic/categories/`.

Cambalache has a proper Gnome icon, so won't modify that as stated in theme description.

So we have two non-issues here.
