### ISSUE TITLE
Flatpak apps aren't fully supported.

### ISSUE THREAD

**Issue by Anikmoujegy** [somepaulo/MoreWaita#27]
![Screenshot from 2022-12-29 00-56-18](https://user-images.githubusercontent.com/119772397/209859719-48466a10-a220-4dc4-a024-c3c911de14d6.png)

See symbolic icons are not showing most of the time on flatpak apps with morewaita. With adwaita it works perfectly.

**Comment by dusansimic** [comment]
Duplicate of #17

**Comment by somepaulo** [comment]
Duplicate of #17
