### ISSUE TITLE
Qt icons font

### ISSUE THREAD

**Issue by dusansimic** [somepaulo/MoreWaita#28]
I've realized that Qt icons use a font named Cairo which might not be present on all systems and could cause issues like text going out of the actual icon box depending on what font is picked up from the stack (example below).

![image](https://user-images.githubusercontent.com/12685466/210172513-2ff0d384-2808-4ecf-b6cb-095a48428991.png)

I think either those icons should be made in such a way that the text is not represented as a text but as a path so it would be the same an all installations. An alternative would be to add the used font's as dependencies which is not ideal imho.

**Comment by somepaulo** [comment]
Fixed in git
