### ISSUE TITLE
Suggestion for folder for lutris ''Games'' folder

### ISSUE THREAD

**Issue by EtereosDawn** [somepaulo/MoreWaita#29]
hello, I have a suggestion that the lutris games folder could receive an icon with a joystick
it gets a little dull with this folder without icons. i love this icon theme and i think this would complete

![image](https://user-images.githubusercontent.com/34200212/211130035-b7e201e4-db8d-4a26-adbd-79b5734c51cf.png)

**Comment by somepaulo** [comment]
Added in git. Will update with Gnome 44 to new style folders.
