### ISSUE TITLE
Some useful info about designing icons

### ISSUE THREAD

**Issue by daudix-UFO** [somepaulo/MoreWaita#3]
Hi, I like your icon theme and it's idea, good job!

But there is some things that may help you with making this icon theme even better ;)

- GNOME HIG icon guides

https://developer.gnome.org/hig/guidelines/app-icons.html

- Guide on designing icons by Tobias Bernard - Purism and GNOME designer

https://blogs.gnome.org/tbernard/2019/12/30/designing-an-icon-for-your-app

- Talk about new GNOME icon design by Tobias Bernard - Purism and GNOME designer

https://conf.tube/w/d4875855-cb95-410e-b5c3-ae4cc925a5f7

- The Big App Icon Redesign by Jakub Steiner - Long time designer

https://blog.jimmac.eu/2019/the-big-app-icon-redesign

- Useful apps for design

https://apps.gnome.org/#development

- Some tutorials about inkscape

https://inkscape.org/learn/tutorials

> This is not an issue, sorry

**Comment by somepaulo** [comment]
Thank you, I've read through most of these before I started. You're welcome to contribute if you like.
