### ISSUE TITLE
[Icon Request] LibreOffice 7.5 Icons

### ISSUE THREAD

**Issue by GittyMac** [somepaulo/MoreWaita#35]
LibreOffice 7.5 introduced [redesigned icons.](https://news.itsfoss.com/libreoffice-7-5-release/) Is it possible to add them to MoreWaita?

**Comment by somepaulo** [comment]
Implemented in [d00f8be](https://github.com/somepaulo/MoreWaita/commit/d00f8be6673e476420ad08f9698e8caca00ab229)
