### ISSUE TITLE
[Icon request] Clojure (clj, cljs, cljc, edn)

### ISSUE THREAD

**Issue by Bu156** [somepaulo/MoreWaita#38]
- Clojure (and edn, a subset of Clojure; like JSON for JavaScript) source and compiled files
I know that Clojure uses the `text/x-clojure` for .clj files, but I had trouble finding the mimetypes for the other formats. I'm unsure of where to look for these.
In my opinion, it'd be preferable to make Clojure source files distinct from .cljc files and especially .edn files, as those are often used for configuration.

**Comment by somepaulo** [comment]
All mimetypes supported by a distro are usually defined in `/usr/share/mime/`. I can't seem to find anything on my Arch searching this folder and subfolders for `clojure` or `clj`. Nor can I find any such mimetype icons in `Papirus`, which , to my knowledge, is the most complete icon theme out there.

Do you know of any icon theme that has support for these mimetypes?

**Comment by somepaulo** [comment]
I might've finally nailed this one. Found four possible mime types for Clojure. They don't seem to work out of the box, since my system (Arch) doesn't list them in its `/etc/mime.types`. Maybe installing the language adds the mime types to the system? Don't have time to test. Feel free to reopen.
