### ISSUE TITLE
[Icon request] Liferea

### ISSUE THREAD

**Issue by gregorydk** [somepaulo/MoreWaita#41]
Liferea
net.sourceforge.liferea, liferea.svg
https://github.com/lwindolf/liferea/blob/master/pixmaps/scalable/net.sourceforge.liferea.svg

![net sourceforge liferea](https://user-images.githubusercontent.com/7804464/219884792-a9ac5208-0e28-4f6d-a052-9694d0b3ac78.png)

**Comment by somepaulo** [comment]
Done
