### ISSUE TITLE
[Icon Request] FlightGear

### ISSUE THREAD

**Issue by dch82** [somepaulo/MoreWaita#45]
The icons folder for Flightgear:
![image](https://user-images.githubusercontent.com/126612878/225441965-a53d743c-e0ef-4a03-93e1-72309e4d9d2d.png)

Inside *N*x*N*/apps, there is `fgcom.png` and `flightgear.png`.
Inside scalable/apps, there is `fgcom.svg` and `flightgear.svg`.

flightgear.svg:
![image](https://raw.githubusercontent.com/FlightGear/flightgear/cf4801e11c5b69b107f87191584eefda3c5a9b26/icons/scalable/apps/flightgear.svg)

fgcom.svg:
![image](https://raw.githubusercontent.com/FlightGear/flightgear/cf4801e11c5b69b107f87191584eefda3c5a9b26/icons/scalable/apps/fgcom.svg)

**Comment by somepaulo** [comment]
Done.
