### ISSUE TITLE
Folder icons in GNOME 44

### ISSUE THREAD

**Issue by awumii** [somepaulo/MoreWaita#46]
GNOME 44 has updated the Adwaita icon theme with redesigned folder icons

Comparison (default folder icon on the left, one of MoreWaita folder icons on the right):
![folder](https://user-images.githubusercontent.com/29680081/226878243-5e6cf74c-6353-4b6b-85be-ba9ddd5ab23d.svg) ![folder-games](https://user-images.githubusercontent.com/29680081/226878754-2109af0f-97c7-4b1d-957b-86cd7ead7464.svg)
![Zrzut ekranu z 2023-03-22 11-37-
30](https://user-images.githubusercontent.com/29680081/226878603-bf76d64c-725f-4f9f-8b39-fb14499140c5.png)

**Comment by somepaulo** [comment]
This is already in the works and will be released this week. The icons are different though, to match the new style.
