### ISSUE TITLE
[Icon request] GitKraken & JOSM

### ISSUE THREAD

**Issue by RedAuburn** [somepaulo/MoreWaita#49]
- [ ] GitKraken
GitKraken.svg, gitkraken.svg, com.axosoft.GitKraken.svg
https://www.gitkraken.com/wp-content/uploads//2021/06/gitkraken-keif-mono-teal-sq.svg
<img width="128px" src="https://user-images.githubusercontent.com/26939824/228032889-2493fb4f-fa01-42c4-9b89-abedb3aa356a.svg">

- [ ] JOSM
josm.svg, org.openstreetmap.josm.svg
https://commons.wikimedia.org/wiki/File:JOSM_Logotype_2019.svg
<img width="128px" src="https://user-images.githubusercontent.com/26939824/228033113-5001f88c-eebd-4a88-aea4-f88fca7bd53f.svg">

**Comment by somepaulo** [comment]
Done
