### ISSUE TITLE
Separate directory for the flatpak symlinks?

### ISSUE THREAD

**Issue by Adaoh2** [somepaulo/MoreWaita#5]
Maybe separating the symlinks for the flatpaks and the real SVG files could help with organisation in the long term

**Comment by dusansimic** [comment]
Interesting idea but I'm not sure it would be good for maintaining the usual structure of the icons theme. That way icons would be stored all in one place and links where GNOME or any other DE expects them to be but I don't see how it will help with maintenance in the long term. It does make sense if you want to separate real icons from links but that doesn't necessarily mean it would help out. You would just have two copies of `apps`, `panel`, `places` and `status` directories and their structures to store the real icons (a storage part) and to store the links to them (the real part that would be used by DE). To me it seems a bit more complicated.

**Comment by somepaulo** [comment]
That would end up creating more mess.
