### ISSUE TITLE
[Icon request] KeePassXC - Cross-platform Password Manager

### ISSUE THREAD

**Issue by wroyca** [somepaulo/MoreWaita#51]
https://keepassxc.org/

https://commons.wikimedia.org/wiki/File:KeePassXC.svg

- [ ] org.keepassxc.KeePassXC.svg
- [ ] org.keepassxc.KeePassXC-locked.svg
- [ ] org.keepassxc.KeePassXC-unlocked.svg

MIME:
- [ ] org.keepassxc.KeePassXC-application-x-keepassxc.svg

---

<img src="https://user-images.githubusercontent.com/91024200/232330033-45f65a62-e19b-45a6-85eb-5b9f015a882d.svg" style="max-width: 100%;" width="48px">

<img src="https://user-images.githubusercontent.com/91024200/232330035-c4f92c04-78bc-4f6a-8c7b-47f63553dd6d.svg" style="max-width: 100%;" width="48px">

<img src="https://user-images.githubusercontent.com/91024200/232330036-33428ecc-51e3-44ff-a364-f7b5517d5d03.svg" style="max-width: 100%;" width="48px">

<img src="https://user-images.githubusercontent.com/91024200/232330107-5d1fd4a6-f3c2-4a27-b36a-8d1b56658a25.svg" style="max-width: 100%;" width="48px">

**Comment by lmcj-xyz** [comment]
I would argue that the _locked_ and _unlocked_ versions are not really necessary since those are most commonly used either by the browser extension and as tray icons. If used as tray icons I believe those should be only the symbolic versions, does that make sense?

**Comment by wroyca** [comment]
> I would argue that the _locked_ and _unlocked_ versions are not really necessary since those are most commonly used either by the browser extension and as tray icons. If used as tray icons I believe those should be only the symbolic versions, does that make sense?

That's fine by me, thought in fairness I believe it's hold it's importance to be pedantic for proper correctness when it comes to an icon theme striving for such fidelity. If we start cutting corners, it becomes uncertain when and where we should draw the line. \:)

**Comment by lmcj-xyz** [comment]
> That's fine by me, thought in fairness I believe it's hold it's importance to be pedantic when it comes to an icon theme striving for such fidelity. If we start cutting corners, it becomes uncertain when and where we should draw the line. :)

I agree, it would be just be a matter of making them symbolic and add them into the `./panel` directory. 

Also, in the last release I saw there are already mimes for _KeePassXC_, which are shared by _KeePass_ and _KeePassX_. That makes sense to me because all those programs use the same type of databases. So I guess that bit can be crossed. Progress!

**Comment by somepaulo** [comment]
Fixed by commit and post-commit complete rework.
