### ISSUE TITLE
Add guide on how to apply custom icons for folders / directories

### ISSUE THREAD

**Issue by 2zqa** [somepaulo/MoreWaita#56]
It seems like there are a few places icons, however it is unclear on how to apply them. I looked in the README file and a bit in the source code, but I couldn't find anything in a few minutes. I think a sentence or two in the README could help many people out who want to quickly apply these custom icons to their directories.

P.S. the icons are awesome!

**Comment by somepaulo** [comment]
Thanks for bringing it up.
Custom folders are not part of xdg desktop specifications, so they can't be assigned custom icons automatically.
The only way to do it is manually through Files (Nautilus). I've added a quick guide to the readme.
Please bear in mind, that the icons are assigned directly, meaning your modified folder will always use the icon you assign to it, and won't change to a smaller icon in list view nor display a custom symbolic icon in bookmarks (it'll be a regular folder icon).
