### ISSUE TITLE
VS Code icon is not applied, every other icon is.

### ISSUE THREAD

**Issue by trbntwo** [somepaulo/MoreWaita#57]
Every icon besides  the VS Code icon is applied. VS Code is installed as native package on Fedora 38 via the VS Code Repository. Is this intended behaviour?

**Comment by somepaulo** [comment]
No, this is not by design. I is VSCode myself. Can you check your `.desktop` launcher and which icon it references?

**Comment by trbntwo** [comment]
It seems that a standard vscode icon is referenced, the `.dektop` file looks like this:
```
[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --unity-launch %F
Icon=vscode
Type=Application
StartupNotify=false
StartupWMClass=Code
Categories=TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-code-workspace;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/share/code/code --new-window %F
Icon=vscode
```

**Comment by somepaulo** [comment]
OK. The name `vscode` wasn't among the relevant symlinks. Please try the current git version (not release). It should be sorted now.

**Comment by trbntwo** [comment]
i tried the git version and it worked, thank you!
