### ISSUE TITLE
Most icons too flat and don't follow Adwaita color scheme

### ISSUE THREAD

**Issue by developer91234** [somepaulo/MoreWaita#59]
This theme doesn't really look like Adwaita because the colors and shape don't follow the Gnome vibe. They still look basically like typical flat mobile os icons. Take a look at Kate for example, the blue color is from from KDE and would never be used in a Gnome. To make it Adwaita, you'd have to change to a deeper or more muted shade of blue.

I'd suggest warmer or more muted tones, rounder edges for the your standard square icons, and more use of gradients. Then this will be like Adwaita

**Comment by somepaulo** [comment]
As far as shapes are concerned, most MoreWaita icons are actual GNOME icons with colours and/or details reworked. So the flatness and roundedness is exactly Adwaita.

As far as colours go, if you read about the purpose of MoreWaita, you'll see that it's to keep icons as close to the original as possible, while giving them a GNOME touch so they blend in more easily.

So to recap, the first part of your statement is untrue, the second, while mostly true (look at all the Gnome Circle icons), doesn't apply to MoreWaita as it contradicts it's purpose.

You're always welcome to fork though.
