### ISSUE TITLE
Icon request: Kitty

### ISSUE THREAD

**Issue by wroyca** [somepaulo/MoreWaita#64]
### Name of app

Kitty

### Link to official icon

https://github.com/kovidgoyal/kitty/blob/master/logo/kitty.svg

### Optional image of the app icon

![kitty](https://github.com/somepaulo/MoreWaita/assets/91024200/369db60e-c767-4e5d-95b4-48555ec6578a)

### Additional context

Kitty is designed from the ground up to support all modern terminal features, such as Unicode, true color, bold/italic fonts, text formatting, etc. It even extends existing text formatting escape codes, to add support for features not available elsewhere, such as colored and styled (curly) underlines.

https://sw.kovidgoyal.net/kitty/
https://github.com/kovidgoyal/kitty

**Comment by somepaulo** [comment]
Added
