### ISSUE TITLE
Installation Instructions not available on ``https://copr.fedorainfracloud.org/coprs/dusansimic/themes/``

### ISSUE THREAD

**Issue by AlbertSolomon** [somepaulo/MoreWaita#66]
I have recently come across the themes hosted at `https://copr.fedorainfracloud.org/coprs/dusansimic/themes/` and noticed that the installation instructions are currently missing or unavailable. As someone who is interested in using these themes to enhance the visual experience on my Fedora-based system, I find this to be a significant obstacle 😔.

**Comment by dusansimic** [comment]
The installation instructions are the same as for any COPR repository:

1. Enable COPR repository (instructions are available on the page you've linked)
2. Install the package you want (you can find the package name in the Packages tab of the repository)

We could add short instructions to help out newbies tho.

**Comment by somepaulo** [comment]
I've updated the README here, but the COPR repo page itself says:

> Installation Instructions  
> 
> Instructions not filled in by author. Author knows what to do. Everybody else should avoid this repo.

Maybe it would be a good idea to add a couple of lines there, like:

> 1. Enable COPR repository: `dnf copr enable dusansimic/themes`
> 2. Install the package you want: `dnf install [package-name]`

**Comment by dusansimic** [comment]
Resolved on the copr page too.
