### ISSUE TITLE
shopt doesn't work in script

### ISSUE THREAD

**Issue by gregorydk** [somepaulo/MoreWaita#71]
shopt is bash only.

Solution:

Change `#!/bin/sh` to `#!/bin/bash`. On many systems `sh` is a symlink to another shell like dash or zsh.

**Comment by erlefloch** [comment]
I had the same issue (shopt didn't work, when using the local install script on Debian 12) and indeed, changing `#!/bin/sh` to `#!/bin/bash` solved it. Maybe you could make a pull request for this @gregorydk ?
