### ISSUE TITLE
Icon request: VSCodium

### ISSUE THREAD

**Issue by gregorydk** [somepaulo/MoreWaita#73]
### Name of app

VSCodium

### Link to official icon

https://github.com/VSCodium/vscodium/blob/master/icons/stable/codium_cnl.svg

### Optional image of the app icon

![com vscodium codium](https://github.com/somepaulo/MoreWaita/assets/7804464/fbabaf72-c481-4c45-b939-c58438dd1c06)

### Additional context

VSCodium icon had a (small) redesign.

**Comment by erlefloch** [comment]
Isn't it rather an update request, as there is already a [morewaita icon for vscodium](https://github.com/somepaulo/MoreWaita/blob/main/apps/scalable/vscodium.svg) ?

**Comment by somepaulo** [comment]
Icon updated in git version
