### ISSUE TITLE
Icon request: DaVinci Resolve

### ISSUE THREAD

**Issue by deusnovus** [somepaulo/MoreWaita#77]
### Name of app

DaVinci Resolve

### Link to official icon

https://upload.wikimedia.org/wikipedia/commons/4/4d/DaVinci_Resolve_Studio.png

### Optional image of the app icon

<img width="512" alt="DaVinci_Resolve_Studio" src="https://github.com/somepaulo/MoreWaita/assets/32219080/d69a742b-53bd-4e8b-8078-736ae7c056c7">

**Comment by somepaulo** [comment]
Added
