### ISSUE TITLE
Icon request: Scribus

### ISSUE THREAD

**Issue by gregorydk** [somepaulo/MoreWaita#80]
### Name of app

Scribus

### Link to official icon

https://en.wikipedia.org/wiki/Scribus#/media/File:Scribus_logo.svg

### Optional image of the app icon

![net scribus Scribus](https://github.com/somepaulo/MoreWaita/assets/7804464/79a57ee7-3823-4588-b4f0-64004d519f75)

### Additional context

Icon names:
scribus
 net.scribus.Scribus

**Comment by somepaulo** [comment]
Added
