### ISSUE TITLE
Icon request: Thunderbird

### ISSUE THREAD

**Issue by Anikmoujegy** [somepaulo/MoreWaita#85]
### Name of app

Thunderbird

### Link to official icon

https://upload.wikimedia.org/wikipedia/commons/5/53/Thunderbird_2023_icon.png

**Comment by Anikmoujegy** [comment]
but the new icon is totally different and I prefer the new one.

**Comment by Anikmoujegy** [comment]
![image](https://github.com/somepaulo/MoreWaita/assets/119772397/120a8221-fc1a-43f8-942b-6e542522ecbd)

**Comment by Anikmoujegy** [comment]
Isn't it much better ???

**Comment by dusansimic** [comment]
The icon is updated (https://github.com/somepaulo/MoreWaita/pull/83/files). I'm not sure what's the new icon you're talking about.
