### ISSUE TITLE
Icon request: Code::Blocks

### ISSUE THREAD

**Issue by asuka909** [somepaulo/MoreWaita#87]
### Name of app

Code::Blocks

### Link to official icon

https://upload.wikimedia.org/wikipedia/commons/4/4b/Codeblocks_logo.png

### Optional image of the app icon

![图片](https://github.com/somepaulo/MoreWaita/assets/64319186/7ac60d2e-5d74-4b31-81d4-a09967cd7c0d)

**Comment by somepaulo** [comment]
Added
