### ISSUE TITLE
Icon request: Xournal++ mimetype

### ISSUE THREAD

**Issue by Slomo17** [somepaulo/MoreWaita#89]
### Name of app

Xournal++

### Link to official icon

https://upload.wikimedia.org/wikipedia/commons/8/8a/Xournal%2B%2B_logo.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

com.github.xournalpp.xournalpp

### Optional image of the app icon

![com github xournalpp xournalpp](https://github.com/somepaulo/MoreWaita/assets/14056946/66487da0-0dc8-4a1f-a971-7aae8c1b3a87)

### Additional context

App icon seems to follow Adwaita guidelines, however there is no mimetype icon for .xopp files

**Comment by somepaulo** [comment]
Added
