### ISSUE TITLE
Icon request: JupyterLab

### ISSUE THREAD

**Issue by erlefloch** [somepaulo/MoreWaita#90]
### Name of app

JupyterLab

### Link to official icon

https://commons.wikimedia.org/wiki/File:Jupyter_logo.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

jupyterlab

### Optional image of the app icon

![image](https://github.com/somepaulo/MoreWaita/assets/90708860/fe627113-f503-46d8-8d18-2132bcd0b66e)

### Additional context

When installing JupyterLab through `pip install jupyterlab`, it nicely creates a desktop entry. Its content is as follows:
```
[Desktop Entry]
Name=JupyterLab
Comment=Run JupyterLab
Exec=jupyter-lab %f
Terminal=true
Type=Application
Icon=jupyterlab
StartupNotify=true
MimeType=application/x-ipynb+json;
Categories=Development;Education;
Keywords=python;
```

So the name of the icon of the server version on PyPI is `jupyterlab`. However on flathub the name of the electron  version is `org.jupyter.JupyterLab`.

**Comment by somepaulo** [comment]
Added
