### ISSUE TITLE
Icon request:  Clapper

### ISSUE THREAD

**Issue by gfigueroap** [somepaulo/MoreWaita#91]
### Name of app

Clapper

### Link to official icon

https://github.com/Rafostar/clapper/blob/master/data/com.github.rafostar.Clapper.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

com.github.rafostar.Clapper

### Optional image of the app icon

An idea for a HIG-compliant icon. Check Additional Context for more details.

![](https://user-images.githubusercontent.com/1908896/125483782-60352786-35ac-4d0d-9d46-833280bba199.png)

### Additional context

There is a conversation in the app's github about [updating to a new icon](https://github.com/Rafostar/clapper/issues/92) which will feature an Adwaita-styled new icon. Hasnt been implemented yet due to not currently being a priority for the project. Id say we could implement it here until it becomes the official icon, which we would eventually remove from this pack when that happens.

**Comment by somepaulo** [comment]
There's no sources files for the icon in that issue. I asked the author. If they don't contribute the icon, I'll do a modified PiTiVi version of it.

**Comment by bertob** [comment]
To be perfectly clear, this is in no way an endorsement of themes :D  

![com github rafostar Clapper Source](https://github.com/somepaulo/MoreWaita/assets/1908896/fab1faa6-3862-49f5-8116-2edb6f742752)

**Comment by somepaulo** [comment]
> To be perfectly clear, this is in no way an endorsement of themes :D

Thank you!!!
I'll remove this from the theme as soon as there's an actual new Gnome compliant icon in Clapper itself. We're only themeing 3rd party icons that feel out of place in Gnome Shell.

**Comment by somepaulo** [comment]
Added
