### ISSUE TITLE
Icon request: Different Hard Drive Types

### ISSUE THREAD

**Issue by Mossy93** [somepaulo/MoreWaita#92]
### Name of app

Hard Drives

### Link to official icon

N/A

### Optional image of the app icon

I would like to see some icons for various drive types. Specifically a SSD and a NVME drive.

### Additional context

These are not for an app. These are just location icons to help me tell the difference in my drives.

**Comment by somepaulo** [comment]
AFAIK, there is no way to reference different types of hard disks. The system differentiates between local, network, and removable drives, so different icons can be assigned to that. Also different types of memory cards. But I haven't seen any reference to different type of hard drive types. If you know how to reference those, please point me in the right direction.

**Comment by Mossy93** [comment]
> AFAIK, there is no way to reference different types of hard disks. The system differentiates between local, network, and removable drives, so different icons can be assigned to that. Also different types of memory cards. But I haven't seen any reference to different type of hard drive types. If you know how to reference those, please point me in the right direction. 

I agree with you there, but we can always right click and customize the icon for each device. I currently have one NVME and one HDD aside from my root drive. It would be nice to have the option to set different icons for the different drives to help me visibly see the difference

**Comment by somepaulo** [comment]
I'll think of a way to graphically represent those. Any suggestions like icons from other themes are welcome.

**Comment by somepaulo** [comment]
Found a name for solid state drives and added an icon for that.  
I'll close this for now. Feel free to reopen if you find more icon names.
