### ISSUE TITLE
Icon request: KolourPaint

### ISSUE THREAD

**Issue by end-4** [somepaulo/MoreWaita#93]
### Name of app

KolourPaint

### Link to official icon

https://upload.wikimedia.org/wikipedia/commons/d/dc/Breezeicons-apps-48-kolourpaint.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

kolourpaint, org.kde.kolourpaint

### Optional image of the app icon

![Breezeicons-apps-48-kolourpaint](https://github.com/somepaulo/MoreWaita/assets/97237370/8077ffb0-fff8-41ab-b6f7-27df7164430a)

**Comment by somepaulo** [comment]
Added
