### ISSUE TITLE
Icon proposals

### ISSUE THREAD

**Issue by untermensch** [somepaulo/MoreWaita#94]
Monero wallet, Yandex browser, Session messenger, Tor(redesign of the original MoreWaita Icon)
![Monero-wallet](https://github.com/somepaulo/MoreWaita/assets/35326326/64508630-a127-4d48-a208-46ab843d2c3a)
![ry yandex browser](https://github.com/somepaulo/MoreWaita/assets/35326326/232a8637-9608-4c6f-88e6-5be3a2ec4554)
![tor-browser](https://github.com/somepaulo/MoreWaita/assets/35326326/8e7f9ec5-1b8a-43ff-b9b6-7b50b76c95fb)
![session-messenger](https://github.com/somepaulo/MoreWaita/assets/35326326/3c02ac27-ee74-4b67-b813-e8307e9ea98f)

**Comment by somepaulo** [comment]
Thank you!
Session is already done in the theme.
I'll think of the other ones in the next dev stage.

**Comment by Draculah** [comment]
Just a note: with the release of Tor Browser 13.0, they released a refinement of the logo on October 13 ([source](https://blog.torproject.org/new-release-tor-browser-130/)). It looks much better now (compared to the old Tor Browser logo) with the shadow in the union in my opinion! :)
