### ISSUE TITLE
Icon request: Pulsar

### ISSUE THREAD

**Issue by mdwalters** [somepaulo/MoreWaita#95]
### Name of app

Pulsar

### Link to official icon

https://raw.githubusercontent.com/pulsar-edit/pulsar/5f3e40a2f5369f8cedad9ee42c747709241e34a1/resources/app-icons/beta.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

pulsar

**Comment by somepaulo** [comment]
Added in git
