### ISSUE TITLE
Automatically install system wide when running w/ root

### ISSUE THREAD

**Issue by wolf-yuan-6115** [somepaulo/MoreWaita#96]
When running `local-install.sh`, is it possible to make it automatically switch to system install when running with `sudo`?

Maybe it's possible to implement, just check if UID is 0

**Comment by somepaulo** [comment]
Good idea. Thanks.
This makes having two separate install scripts obsolete though.
Unified the two install scripts into `install.sh` and updated install instructions: run with `sudo` for system-wide installation, run without it for local.
