### ISSUE TITLE
Icon request: Setzer

### ISSUE THREAD

**Issue by kinten108101** [somepaulo/MoreWaita#97]
### Name of app

Setzer

### Link to official icon

https://raw.githubusercontent.com/cvfosammmm/Setzer/master/data/org.cvfosammmm.Setzer.svg

### Name of icon (as referenced in the .desktop file, regular and Flatpak apps have different icon names for the same apps)

setzer, org.cvfosammmm.Setzer

**Comment by somepaulo** [comment]
Added
