### ISSUE TITLE
local-install.sh fails on Debian

### ISSUE THREAD

**Issue by N0NB** [somepaulo/MoreWaita#98]
This is more of an FYI for those running Debian and trying the manual installation method.

I see you are developing this on Arch Linux and there `/usr/bin/sh` is a symbolic link to `/usr/bin/bash` which causes this script to fail on Debian as it uses "Dash" for `sh` which does not understand so-called Bashisms.

The error received on Debian is:

``` console
$ ./local-install.sh 
./local-install.sh: 4: shopt: not found
./local-install.sh: 5: Syntax error: "(" unexpected
```

The following patch will enable the script to run on Debian:

``` diff

diff --git a/local-install.sh b/local-install.sh
index eb0b07e..3f6b182 100755
--- a/local-install.sh
+++ b/local-install.sh
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 mkdir -p ~/.local/share/icons/MoreWaita/
 shopt -s extglob
```

The icon package is now installed and available in Tweaks.

**Comment by somepaulo** [comment]
Oops, sorry. This was fixed long ago in the system install script, but overlooked in the local one. Now fixed in git and will make it to the next point release in a few weeks.
